### ISSUE TITLE
Terraform 13 Error: Invalid provider registry host

### ISSUE THREAD

**Issue by jknott-terraform** [hashicorp/terraform-provider-kubernetes-alpha#102]
Error: Invalid provider registry host

The given source address "github.com/hashicorp/kubernetes-alpha" specifies a
GitHub repository rather than a Terraform provider. Refer to the documentation
of the provider to find the correct source address to use.

Here is what I have in terraform block

     kubernetes-alpha = {
       //      // https://github.com/hashicorp/terraform-provider-kubernetes-alpha
       source  = "github.com/hashicorp/kubernetes-alpha"
       #version = "0.1.0"
     }

**Comment by aareet** [comment]
@jknott-terraform you're too quick for us :) We're working on publishing to the registry as we speak. #58 and #85

**Comment by jknott-terraform** [comment]
Thank you! Could you post the source of the repo when you get finished so I can test/use it? Thanks

**Comment by aareet** [comment]
Here you go: https://registry.terraform.io/providers/hashicorp/kubernetes-alpha/latest

I'll close this issue for now, let us know if you encounter any other issues.
