### ISSUE TITLE
Update docs to include install from Terraform Registry

### ISSUE THREAD

**Issue by Redeux** [hashicorp/terraform-provider-kubernetes-alpha#106]
### Description

The readme only specifies how to install the provider manually. 

### References

https://registry.terraform.io/providers/hashicorp/kubernetes-alpha/latest

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
The PR title doesn't say so but https://github.com/hashicorp/terraform-provider-kubernetes-alpha/pull/104 should fix - @Redeux please review
