### ISSUE TITLE
cant scale deployed resources

### ISSUE THREAD

**Issue by vrabbi** [hashicorp/terraform-provider-kubernetes-alpha#112]
### Terraform Version and Provider Version
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.1
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.0

### Kubernetes Version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

### Affected Resource(s)
- kubernetes_manifest
- CAPI Machine Deployment

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this. -->

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "machinedeployment_0" {
  provider = kubernetes-alpha
  manifest = {
    "apiVersion" = "cluster.x-k8s.io/v1alpha3"
    "kind" = "MachineDeployment"
    "metadata" = {
      "labels" = {
        "cluster.x-k8s.io/cluster-name" = var.cluster_name
      }
      "name" = "${var.cluster_name}-md-0"
      "namespace" = var.namespace
    }
    "spec" = {
      "clusterName" = var.cluster_name
      "replicas" = tonumber(var.worker_node_count)
      "selector" = {
        "matchLabels" = {}
      }
      "template" = {
        "metadata" = {
          "labels" = {
            "cluster.x-k8s.io/cluster-name" = var.cluster_name
          }
        }
        "spec" = {
          "bootstrap" = {
            "configRef" = {
              "apiVersion" = "bootstrap.cluster.x-k8s.io/v1alpha3"
              "kind" = "KubeadmConfigTemplate"
              "name" = "${var.cluster_name}-md-0"
            }
          }
          "clusterName" = var.cluster_name
          "infrastructureRef" = {
            "apiVersion" = "infrastructure.cluster.x-k8s.io/v1alpha3"
            "kind" = "VSphereMachineTemplate"
            "name" = var.cluster_name
          }
          "version" = var.k8s_version
        }
      }
    }
  }
  wait_for = {
    fields = {
      "status.phase" = "Running"
    }
  }
}
```
### Expected Behavior
What should have happened?
Terraform should scale the machine deployment
### Actual Behavior
What actually happened?
fails to keep integer format correctly and cant scale
### Steps to Reproduce

Cluster API for vSphere Clusters are being deployed. this is running against kind clusters

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Thanks for opening @vrabbi. Could you provide us with a gist of the terraform run with `TF_LOG=TRACE` enabled?

**Comment by aareet** [comment]
Closing - it has been about 4 months
