### ISSUE TITLE
Terraform crashes with https://github.com/hashicorp/terraform-provider-kubernetes-alpha

### ISSUE THREAD

**Issue by linuxbsdfreak** [hashicorp/terraform-provider-kubernetes-alpha#115]
### Terraform Version and Provider Version
```
terraform --version

Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.0
```

### Kubernetes Version
```
kubectl version                                       
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-26T20:32:49Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.8", GitCommit:"35dc4cdc26cfcb6614059c4c6e836e5f0dc61dee", GitTreeState:"clean", BuildDate:"2020-06-26T03:36:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### References
https://github.com/hashicorp/terraform/issues/26230

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
I believe this issue should be fixed by https://github.com/hashicorp/terraform-provider-kubernetes-alpha/pull/92

It has already been merged, so if you have the opportunity to test with a build from master I'd appreciate the feedback. If not, a release is coming in the next couple of days.

**Comment by linuxbsdfreak** [comment]
Hi @alexsomesan ,

It is fixed. 

```
terraform --version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.1
+ provider registry.terraform.io/hashicorp/null v2.1.2


terraform {
  required_version = ">= 0.13.0"
  required_providers {
    kubernetes-alpha = "~> 0.2.1"
  }
}

provider "kubernetes-alpha" {
 server_side_planning = true
 config_path = var.robotkubeconfig
}
```

Before the bug was present i had to provide  the compete path to the kubeconfig and could not provide it via a variable path.
