### ISSUE TITLE
Provider path to a K8s manifest or template file to the manifest key in the kubernetes_manifest 

### ISSUE THREAD

**Issue by linuxbsdfreak** [hashicorp/terraform-provider-kubernetes-alpha#117]
### Description

The present configuration of the terraform provider allows the K8s manifest as a Terraform Map as inline with the **manifest** key. It would be nice to provide path to the k8s manifests as a terraform map or a template file. 

### Potential Terraform Configuration

main.tf
```
resource "kubernetes_manifest" "test-configmap" {
  provider = kubernetes-alpha

   manifest = templatefile("${path.module}/templates/configmap.tmpl", {
          shoot_cluster_name = var.shoot_cluster_name,
          project_name = var.project_name,
   })
}
```

configmap.tmpl
```
 {
    "apiVersion" = "v1"
    "kind" = "ConfigMap"
    "metadata" = {
      "name" = shoot_cluster_name
      "namespace" = project_name
    }
    "data" = {
      "foo" = "bar"
    }
  }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by linuxbsdfreak** [comment]
@alexsomesan . Is this possible to externalize the manifest to a file ? This would prevent populating the main.tf with large CRs and load needed ones based on conditionals. My ideal wish would be to have a single base template/file to keep it DRY and then have small snippets to be added to the base template based on conditions. This would simplify the terraform code in the module.

**Comment by alexsomesan** [comment]
Hi, 

We've actually detailed a way to do just what you're asking for in the announcement blog post for this provider.
Have a look here: https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform

**Comment by linuxbsdfreak** [comment]
Hi @alexsomesan 

Do you mean this ? 

`echo 'yamldecode(file("my-manifest-file.yaml"))' | terraform console` 

I was imagining on the lines of providing a template file or path to a raw K8s yaml manifest within terraform code as show above 

At the moment the K8s CR yaml is quite large and would like to make different templates and load it conditionally, which would make the main.tf quite smaller and easier to read.   

Kevin
