### ISSUE TITLE
Alpha Provider can't handle CustomResourceDefinitions and Namespace dependencies in one plan

### ISSUE THREAD

**Issue by martin-schaefer** [hashicorp/terraform-provider-kubernetes-alpha#125]
### Terraform Version and Provider Version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.2
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.2.1

### Kubernetes Version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

### Affected Resource(s)
Namespaces and CustomResourceDefinitions

### Terraform Configuration Files
https://github.com/martin-schaefer/terraform-modules

### Expected Behavior
Terraform should recognize the dependencies between the Namespaces, the CustomResourceDefinitions (CRD's) and the actual created resources based on those CRD's.

### Actual Behavior
terraform plan shows this error messages:

Error: rpc error: code = Unknown desc = no matches for operators.coreos.com/v1, Resource=OperatorGroup
Error: rpc error: code = Unknown desc = no matches for operators.coreos.com/v1alpha1, Resource=CatalogSource
Error: rpc error: code = Unknown desc = update dry-run for 'olm/catalog-operator' failed: namespaces "olm" not found
Error: rpc error: code = Unknown desc = no matches for operators.coreos.com/v1alpha1, Resource=ClusterServiceVersion
Error: rpc error: code = Unknown desc = no matches for operators.coreos.com/v1, Resource=OperatorGroup
Error: rpc error: code = Unknown desc = update dry-run for 'olm/olm-operator-serviceaccount' failed: namespaces "olm" not found
Error: rpc error: code = Unknown desc = update dry-run for 'olm/olm-operator' failed: namespaces "olm" not found

### Steps to Reproduce
- Checkout https://github.com/martin-schaefer/terraform-modules and navigate to it's root directory containing the file `example.tf`
- Start a minikube instance
- Run `terraform init` -> OK
- Run `terraform validate` -> OK
- Run `terraform plan` -> Errors as shown above

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by martin-schaefer** [comment]
It is probably the same issue as #52

**Comment by martin-schaefer** [comment]
I've also tried it with `server_side_planning = false` but there are still errors:

```
Error: rpc error: code = Unknown desc = failed to determine resource GVR: no matches for operators.coreos.com/v1alpha1, Resource=ClusterServiceVersion

Error: rpc error: code = Unknown desc = failed to get resource type from OpenAPI (ID io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition): unknown type:

Error: rpc error: code = Unknown desc = failed to determine resource GVR: no matches for operators.coreos.com/v1alpha1, Resource=CatalogSource

Error: rpc error: code = Unknown desc = failed to get resource type from OpenAPI (ID io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition): unknown type:

Error: rpc error: code = Unknown desc = failed to get resource type from OpenAPI (ID io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition): unknown type:

Error: rpc error: code = Unknown desc = failed to get resource type from OpenAPI (ID io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition): unknown type:

Error: rpc error: code = Unknown desc = failed to determine resource GVR: no matches for operators.coreos.com/v1, Resource=OperatorGroup

Error: rpc error: code = Unknown desc = failed to determine resource GVR: no matches for operators.coreos.com/v1, Resource=OperatorGroup

Error: rpc error: code = Unknown desc = failed to get resource type from OpenAPI (ID io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition): unknown type:

Error: rpc error: code = Unknown desc = failed to get resource type from OpenAPI (ID io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition): unknown type:
```

**Comment by feliperfmarques** [comment]
I got this error too...

**Comment by dak1n1** [comment]
Thanks for filing this issue. This is a limitation of server-side planning that we're tracking here: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/57. I'm going to close this one as a duplicate, but you can use the :+1: reaction on the original issue to vote for it.
