### ISSUE TITLE
Updating a kubernetes_manifest based resource fails with "conflict with 'okhttp'"

### ISSUE THREAD

**Issue by trietsch** [hashicorp/terraform-provider-kubernetes-alpha#145]
### Terraform, Provider, Kubernetes versions

```
Terraform version: v0.14.0
Provider version: 0.2.1
Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.15-gke.800", GitCommit:"fa6f8f9671a3ba4b1790bac677bb72b04204e8fc", GitTreeState:"clean", BuildDate:"2020-12-21T09:19:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "kafka_user_test" {
  provider = kubernetes-alpha
  manifest = {
    "apiVersion" = "kafka.strimzi.io/v1beta1"
    "kind" = "KafkaUser"
    "metadata" = {
      "labels" = {
        "strimzi.io/cluster" = "test"
      }
      "name" = "test"
      "namespace": var.namespace
    }
    "spec" = {
      "authentication" = {
        "type" = "tls"
      }
      "authorization" = {
        "acls" = [
          {
            host = "*"
            operation = "All"
            resource = {
              "name" = "billing"
              "patternType" = "literal"
              "type" = "topic"
            }
          }
        ]
        "type" = "simple"
      }
    }
  }
}
```

### Debug Output
I've already changed the Terraform code back, so I don't have a complete debug output, though the error that occurred was:
```
 Apply failed with 1 conflict: conflict with "okhttp"
```

### Steps to Reproduce

1. `terraform apply` when the resource does not yet exist
2. `terraform apply` again with some parts of the resource changed. Does not matter which part.

### Expected Behavior
The resource should have been updated

### Actual Behavior
The resource was not updated

### Important Factoids
Running on GKE, see version up top.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
What you are seeing here is an error from the Kubernetes API describing a conflict on one of the fields of the resource that was overwritten by another application in the cluster called "okhttp".
If you look in the `metadata.managedFields` structure of the KafkaUser object (using kubectl get) you will see more details about which particular field is causing this.
The provider right now just registers itself as a field manager for all fields it has set on creation, but it will not handle conflicts at this time. We plan to implement proper field management functionality in the near future, once the basic features of the provider have been stabilised.

In the mean time, you can try omitting  the offending field from the initial resource configuration in Terraform or alternatively configure the okhttp app to not overwrite it.

It would be useful for us if you can share more details about the "okhttp" app so we can try to reproduce this scenario.

Full explanation of the concept of field managers is available here: https://kubernetes.io/docs/reference/using-api/server-side-apply/#field-management

**Comment by trietsch** [comment]
Thanks for the detailed explanation. Makes sense indeed. For now we've decided to use Helm charts for custom resource definitions, but we'll switch to the Kubernetes Alpha provider as soon as this is supported.
