### ISSUE TITLE
kubernetes-alpha should error if installed in an incompatible version of Terraform

### ISSUE THREAD

**Issue by achew22** [hashicorp/terraform-provider-kubernetes-alpha#160]
### Description

According to @aareet in https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/159#issuecomment-796476568, this provider has specific requirements around which versions of Terraform it can be loaded in. It would be nice if kubernetes-alpha validated that it was running on a compatible version before launching. 

### Potential Terraform Configuration

It should fail in all cases when the terraform that loaded it is incompatible.

### References

* https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/159#issuecomment-796476568

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@achew22 Thanks for pointing this out! This is really a good idea and an oversight on our part.
I'll put up a PR to address this right away.

FWIW, this issue is not related to #159
