### ISSUE TITLE
Regression: v0.3.0 is unable to auth against GKE, v0.2.X was able to

### ISSUE THREAD

**Issue by achew22** [hashicorp/terraform-provider-kubernetes-alpha#162]
### Terraform, Provider, Kubernetes versions

Terraform version:

```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.3.0
```

Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.300", GitCommit:"a6af8499b881b1020b39e0c5f3045207f8340c46", GitTreeState:"clean", BuildDate:"2021-02-20T01:41:46Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected Resource(s)

The provider as a whole.

### Terraform Configuration Files

```hcl
provider "kubernetes-alpha" {
  host             = "https://${var.cluster_endpoint}"

  token = data.google_client_config.default.access_token
  cluster_ca_certificate = var.cluster_ca_certificate
}
```

### Debug Output

https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/159 has a large amount of output that can be referred to for this.

### Description

When upgrading from v0.2.X, I was able to use the following code snippet to connect to my GKE instance. In v0.3.0, I am unable to connect in 

Interestingly, the `kubernetes` (not alpha) provider uses a nearly identical block and connects just fine:

```hcl
provider "kubernetes" {
  host             = "https://${var.cluster_endpoint}"

  token = data.google_client_config.default.access_token
  cluster_ca_certificate = var.cluster_ca_certificate
}
```

### Expected Behavior
What should have happened?

* The connection should have succeeded

### Actual Behavior
What actually happened?

* The user doesn't validate and you get errors like

```
User "system:anonymous" cannot get path "/apis"
```

### Important Factoids

* I don't appear to be the only person with this issue. @jbg left a comment (https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/159#issuecomment-796521271) indicating similar issues. @jbc if you could comment on this bug with additional context to help with debugging that would be really helpful.
* This is probably related to the OpenAPI change, but unfortunately I'm having a hard time understanding your testing setup so that I could run a bisect to find the actual commit.

### References

* https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/159

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jbg** [comment]
I'm on AWS EKS. I have three k8s clusters, with aliases for the providers. Each one's providers look like this:

```
provider "kubernetes" {
  alias = "foo"

  host = aws_eks_cluster.foo.endpoint
  token = data.aws_eks_cluster_auth.foo.token
  cluster_ca_certificate = base64decode(aws_eks_cluster.foo.certificate_authority[0].data)
}

provider "kubernetes-alpha" {
  alias = "foo"

  host = aws_eks_cluster.foo.endpoint
  token = data.aws_eks_cluster_auth.foo.token
  cluster_ca_certificate = base64decode(aws_eks_cluster.foo.certificate_authority[0].data)
}
```

Then I pass the providers into a module:

```
module "cert_manager_foo" {
  source = "./modules/cert-manager"

  providers = {
    kubernetes = kubernetes.foo
    kubernetes-alpha = kubernetes-alpha.foo
  }
}
```

The module looks like this:

```
terraform {
  required_version = "0.14.8"

  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "~> 2.0"
    }

    kubernetes-alpha = {
      source = "hashicorp/kubernetes-alpha"
      version = "~> 0.3"
    }
  }
}

resource "kubernetes_manifest" "some_cert_manager_manifest" {
  provider = kubernetes-alpha

  manifest = { ... }
}
```

The `kubernetes` provider works fine with this setup, and the `kubernetes-alpha` provider used to work before 0.3.0. Now it hangs forever during plan and if I enable trace logging I can see the error previously mentioned: `user "system:anonymous" cannot get path "/apis"`

**Comment by jbg** [comment]
Maybe it's just redacted, but I don't see any auth token in the API request in the trace logs from #159:

```
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: ---[ REQUEST ]---------------------------------------
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: GET /api?timeout=32s HTTP/1.1
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Host: 35.239.49.54
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: User-Agent: terraform-provider-kubernetes-alpha_v0.3.0_x5/v0.0.0 (linux/amd64) kubernetes/$Format
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept: application/json, */*
2021-03-11T02:59:43.220Z [DEBUG] plugin.terraform-provider-kubernetes-alpha_v0.3.0_x5: Accept-Encoding: gzip
```

**Comment by achew22** [comment]
I did not redact anything from those logs, those are verbatim.

**Comment by jbg** [comment]
> I did not redact anything from those logs, those are verbatim.

I actually wondered whether maybe the plugin doesn't log the Authorization header to avoid putting tokens in the logs.

**Comment by alexsomesan** [comment]
I can confirm this is an issue. 
A very embarrassing copy-paste error seen here: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/277cbe19cf4e67f568305382dedec1a8ebf5f2ce/provider/configure.go#L366

Working on the fix right now.

**Comment by davidalger** [comment]
@alexsomesan Would it be worth adding a failure mechanism as well, so it won't infinitely loop when receiving `403 Forbidden` replies?

**Comment by alexsomesan** [comment]
Yeah, I'm also looking into fixing that.
Not sure why the bare REST client is retrying ad-nauseam.

**Comment by alexsomesan** [comment]
v0.3.1 is now out and includes the fix for this.
