### ISSUE TITLE
When Installing CRDs (AWS load balancer controller): 'status' attribute key is not allowed in manifest

### ISSUE THREAD

**Issue by nigeisel** [hashicorp/terraform-provider-kubernetes-alpha#164]
### Terraform, Provider, Kubernetes versions

```
Terraform version: v0.14.7
Provider version:
Kubernetes version: v1.17.12-eks-7684af
```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files

I was trying to deploy a manifest containing CRDs for the AWS load balancer controller. 

Minimal example:
```hcl

resource "kubernetes_manifest" "crd" {
  provider = kubernetes-alpha
  manifest = yamldecode(file("${path.module}/aws-lb-controller-crds.yaml"))
}
```
where the content of the file loaded as the manifest is equal to this: https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/crds/crds.yaml

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
It should successfully deploy them.

### Actual Behavior
Terraform fails due to:
```
terraform apply

Error: Forbidden attribute key in "manifest" value

  on serviceaccount.tf line 67, in resource "kubernetes_manifest" "crd":
  67: resource "kubernetes_manifest" "crd" {

'status' attribute key is not allowed in manifest configuration
```
I have no idea why the status attributes in the manifest could be forbidden?

### Important Factoids
This example was run against an AWS EKS cluster (without any EC2 nodes, only Fargate)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by redeux** [comment]
Looks like this is related to #158

**Comment by nigeisel** [comment]
I found that the status code is explicitly forbidden here: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/b2c2776d944bab746ef6b60269dddbabff636b3d/provider/validate.go#L86 but do no understand why.

**Comment by nigeisel** [comment]
@redeux Right, I must have missed that. However, I am not sure if it is the same problem since this seems to be about the existence of a `status` property in general whereas #158 seems to be about empty blocks.

I tried removing this part (with the empty object `status: {} `)
https://github.com/aws/eks-charts/blob/a329f65e2192e7120918fb821a1411065db01f16/stable/aws-load-balancer-controller/crds/crds.yaml#L39

but it still fails, because the `status` attribute occurs also here https://github.com/aws/eks-charts/blob/a329f65e2192e7120918fb821a1411065db01f16/stable/aws-load-balancer-controller/crds/crds.yaml#L163
and here https://github.com/aws/eks-charts/blob/a329f65e2192e7120918fb821a1411065db01f16/stable/aws-load-balancer-controller/crds/crds.yaml#L180

It seems to work if I delete all of them though

**Comment by alexsomesan** [comment]
@nigeisel The error refers to the top-level `status`. The one next to `spec`.
That should not be part of the input manifest. The `subresources.status` one is important. You should keep that in. It signals to the CRD controller that you would like to have a status appended to the resource by the controller / api-server.

**Comment by redeux** [comment]
> @nigeisel The error refers to the top-level `status`. The one next to `spec`.
> That should not be part of the input manifest. The `subresources.status` one is important. You should keep that in. It signals to the CRD controller that you would like to have a status appended to the resource by the controller / api-server.

I would also expect [this status attribute](https://github.com/aws/eks-charts/blob/a329f65e2192e7120918fb821a1411065db01f16/stable/aws-load-balancer-controller/crds/crds.yaml#L163) to work since it's not empty.

**Comment by alexsomesan** [comment]
The top-level status is a "read-only" attribute from the point of view of the user. It will be discarded by the API server anyway. That is the reason why we don't allow it.

**Comment by alexsomesan** [comment]
When I say top-level I actually mean this one: https://github.com/aws/eks-charts/blob/a329f65e2192e7120918fb821a1411065db01f16/stable/aws-load-balancer-controller/crds/crds.yaml#L180

**Comment by alexsomesan** [comment]
Also, @nigeisel you should update Terraform to `0.14.8` otherwise you will see errors with certain resources like Deployments

**Comment by nigeisel** [comment]
@alexsomesan and @redeux Thank you very much for the help and the explanation. That makes sense and I got it to work! I'll close this since this does not seem to be a bug.
