### ISSUE TITLE
Experiment: for schema-less CRDs fall back to dry-run API call for type inferring 

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-provider-kubernetes-alpha#170]
### Description

CRDs in certain applications have been noted to abuse the `preserveUnknownFields` flag to avoid having to specify schema for their CR. Most notably, Traefik before version v2.5 (unreleased) is taking this approach.

For reference, this is how the OpenAPI type of the Traefik IngressRoute custom resource looks like. Note the absence of any Properties or other attribute information.
```
"us.containo.traefik.v1alpha1.IngressRoute": {
    "type": "object",
    "x-kubernetes-group-version-kind": [
        {
            "group": "traefik.containo.us",
            "kind": "IngressRoute",
            "version": "v1alpha1"
        }
    ]
}
```

Because of the lack of schema information, the provider is unable to determine the structure of the CR out of OpenAPI. This leads to those CR types not being manageable with this provider.

To mitigate that, we could explore a fall-back strategy of doing what the previous versions of this provider were doing, namely optimistically making a dry-run API call during planning that would hopefully provider some insight into the structure of the CR. This method has proven to be brittle, and will render incomplete type information which may cause Terraform to refuse the state returned by apply.

The goal of this experiment would be to prove or disprove wether this approach could be usable as fallback for schema-less CRDs.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
The problem that led to this proposal is described here: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/166

**Comment by adawalli** [comment]
@alexsomesan - I ran into this with AWS's CRD for their ENICONFIGS

https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html 

Do you have any clean workarounds we can do until and if this exploration goes through?

**Comment by alexsomesan** [comment]
Release 0.4.0 just went out implementing this.
