### ISSUE TITLE
"Invalid attribute in provider configuration" with dynamic provider configuration

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/terraform-provider-kubernetes-alpha#174]
### Terraform, Provider, Kubernetes versions

```
Terraform version: 0.14.8
Provider version: 0.3.1
Kubernetes version: 1.18.12
```

### Affected Resource(s)

 - Provider configuration

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

data "google_client_config" "default" {
}

data "terraform_remote_state" "gke" {
  backend = "gcs"

  config = {
    bucket = "somebucket"
    prefix = "someprefix"
  }
}


provider "kubernetes-alpha" {
  host                   = data.terraform_remote_state.gke.outputs.endpoint
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.terraform_remote_state.gke.outputs.ca_certificate)
}

```

### Steps to Reproduce

1. `terraform plan` 

### Expected Behavior
What should have happened?

A plan to be displayed.

### Actual Behavior
What actually happened?

```
Invalid attribute in provider configuration

  on main.tf line 6, in provider "kubernetes-alpha":
   6: provider "kubernetes-alpha" {

'host' is not a valid URL


Error: Failed to get RESTMapper client

cannot create discovery client: no client config

ERRO[0003] Hit multiple errors:
```

### Important Factoids

This is a variation of https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/147 that now appears with >= 0.3.1.

### References

- https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/147
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
@lawliet89 The error message tries to be helpful there. It says: `'host' is not a valid URL`

See below the configuration that works in my tests. The only difference I can spot is putting "https://' in front of the value of the endpoint value. In GKE, the endpoint seems to just be an IP address.

```
data "google_client_config" "current" {}

data "terraform_remote_state" "gke" {
  backend = "local"

  config = {
    path = "/Users/alex/work/terraform-provider-kubernetes/kubernetes/test-infra/gke/terraform.tfstate"
  }
}

provider "kubernetes-alpha" {
  token                  = data.google_client_config.current.access_token
  host                   = "https://${data.terraform_remote_state.gke.outputs.cluster_api}"
  cluster_ca_certificate = base64decode(data.terraform_remote_state.gke.outputs.cluster_ca)
}

resource "kubernetes_manifest" "test-configmap" {
  provider = kubernetes-alpha
  manifest = {
    "apiVersion" = "v1"
    "kind"       = "ConfigMap"
    "metadata" = {
      "name"      = "test-config"
      "namespace" = "default"
      "labels" = {
        "app"         = "test-app"
        "environment" = "production"
      }
    }
    "data" = {
      "foo" = "bar"
    }
  }
}
```

Let me know if that works in your case.

**Comment by alexsomesan** [comment]
@davidalger Indeed, the other providers will optimistically try to deduce the URL when parts are omitted. To be fair, that behaviour is undocumented and the official documentation of all three providers does specify this attribute should be a URL.

We'll make changes to align to that behaviour, for consistency.

**Comment by lawliet89** [comment]
@alexsomesan Adding `https://` worked. Thanks! It wasn't very obvious for me TBH. Please feel free to close this issue.
