### ISSUE TITLE
Planning with not fully known values fails with "failed to morph object element into object element"

### ISSUE THREAD

**Issue by achew22** [hashicorp/terraform-provider-kubernetes-alpha#190]
### Terraform, Provider, Kubernetes versions

```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/aws v3.31.0
+ provider registry.terraform.io/hashicorp/google v3.59.0
+ provider registry.terraform.io/hashicorp/google-beta v3.59.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.2
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.3.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-gke.1600", GitCommit:"4f6f69fd81ca8cb6962a2f7e1ed9c7880834cf71", GitTreeState:"clean", BuildDate:"2021-03-08T19:22:13Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

### Affected Resource(s)

`kubernetes_manifest`

### Terraform Configuration Files

I believe this is a self contained, testable sample. If I messed this up, please tell me and I'll improve it.

```
resource "kubernetes_service" "service" {
  metadata {
    name = "name"
    namespace = "namespace"
  }

  spec {
    type = "NodePort"

    port {
      name = "http-server"
      port = 80
      target_port = "http-server"
    }
  }
}

resource "kubernetes_manifest" "https_backend_config" {
  provider = kubernetes-alpha

  manifest = {
    apiVersion = "cloud.google.com/v1"
    kind = "BackendConfig"
    metadata = {
      name = "${var.name}-https"
      namespace = var.namespace
    }

    spec = {
      # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#direct_health
      healthCheck = {
        requestPath: "/healthz"
        type: "HTTP"
        port: kubernetes_service.service.spec[0].port[0].node_port
      }
    }
  }
}
```

### Debug Output

```
Error: Failed to morph manifest to OAPI type

  on file.tf line 22, in resource "kubernetes_manifest" "https_backend_config":
  22: resource "kubernetes_manifest" "https_backend_config" {

[AttributeName("spec")] failed to morph object element into object element:
[AttributeName("spec").AttributeName("healthCheck")] failed to morph object
element into object element:
[AttributeName("spec").AttributeName("healthCheck").AttributeName("port")]
failed to morph object element into object element: cannot morph value that
isn't fully known
```
### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
What should have happened?

It should set the port on the health check to be the port defined in the `kubernetes_service`

### Actual Behavior
What actually happened?

Planning/apply would succeed.

### References

I think this is the implicated line of code.

https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/b2c2776d944bab746ef6b60269dddbabff636b3d/morph/morph.go#L19

Before I get too far down the rabbit hole on this one I wanted to ask a few questions:

1. Is this a necessary check to perform? While we may not know the *value* of `v`, I'm having a tough time coming up with a counterexample where we wouldn't know the *type* of the value. This is likely a place where my imagination is failing me though. 
2. Presuming there are situations where we don't know the type, would it be a bad idea to return the type in the case where there isn't a known value, would it be okay to check if the type then check if it's a known value? To be specific, move

  https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/b2c2776d944bab746ef6b60269dddbabff636b3d/morph/morph.go#L18-L20

  down to right before the return on line `41`?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by carlcauchi** [comment]
@achew22 Many thanks for reporting this issue.
I'm having a similar situation with the mentioned error of:
```
failed to morph object element into object element: cannot morph value that
isn't fully known
```
In my case, this cannot be know before, as the resource needs to be first applied and then it will know the values.

For example in my case, I'm creating an aws resource of type 'eip' and in the kubernetes manifest I'm making reference to this resource to read it's private IP address - which I'm then using its value for a Custom CRD deployment (basically its getting the Private IP address of the elasticsearch nodes, and the setting these IPs in a custom CRD called ClusterOut to be used as the destination servers for cluster logging)

Will this fix handle this scenario? or is there another way to do this?

**Comment by achew22** [comment]
> Will this fix handle this scenario? or is there another way to do this?

Unfortunately, I have no idea. The PR is out there at #191, if you wanna try it out you can clone the repo, `go build .` it and then create a `$HOME/.terraformrc` that looks something like this and try it out. Getting an additional tester would probably advance the PR's legitimacy so I'd welcome any feedback you might have.

```
provider_installation {
  dev_overrides {
    # N.b. this must be the path to the GIT REPO, not the path to the binary.
    "hashicorp/kubernetes-alpha" = "/home/username/terraform-provider-kubernetes-alpha"
  }


  # For all else get them directly from the source.
  direct{}
}
```

**Comment by jbg** [comment]
@carlcauchi it looks like the next release will fix this, but in the meantime a workaround is to plan & apply the creation of the resource with the values (in your case the EIP) and then plan & apply the creation of the k8s manifest that depends on those values.

**Comment by alexsomesan** [comment]
Release v0.3.3 went out yesterday and includes the fix for this issue.
