### ISSUE TITLE
Error: Failed to construct REST client

### ISSUE THREAD

**Issue by anyght** [hashicorp/terraform-provider-kubernetes-alpha#199]
Hello, I have this error when I'm using kubernetest-alpha provider
![image](https://user-images.githubusercontent.com/59748997/117013724-69145200-acf0-11eb-8e0e-a5d2c7abee46.png)

```
terraform {
  required_providers {
    kubernetes-alpha = {
      source = "hashicorp/kubernetes-alpha"
      version = "0.3.2"
    }
  }
}

provider "kubernetes-alpha" {
  host                   = "https://${data.google_container_cluster.primary.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.google_container_cluster.primary.master_auth[0].cluster_ca_certificate)
}

resource "kubernetes_manifest" "test-configmap" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "v1"
    "kind" = "ConfigMap"
    "metadata" = {
      "name" = "test-config"
      "namespace" = "default"
    }
    "data" = {
      "foo" = "bar"
    }
  }
}
```

somebody known this error?

**Comment by alexsomesan** [comment]
@anyght The error message explains that the provider has no valid configuration and thus cannot initialise the API clients.

How does your provider block look like in TF?

**Comment by anyght** [comment]
```
data "google_client_config" "default" {
  depends_on = [
    google_container_cluster.primary,
  ]
}

data "google_container_cluster" "primary" {
  name     = var.cluster_name
  location     = var.location
  depends_on = [
    google_container_cluster.primary,
  ]
}
``` 
it is the same config for kubernetes provider and it work

**Comment by alexsomesan** [comment]
Is `google_container_cluster.primary` (referenced by depends_on) already created at the time when you run the terraform operation that produces this error?

**Comment by anyght** [comment]
> Is `google_container_cluster.primary` (referenced by depends_on) already created at the time when you run the terraform operation that produces this error?

I want to create all resources at the same time, so when I use _terraform plan_, the cluster is not ready yet.
Do you think that the reason for what I have this error?

**Comment by anyght** [comment]
> Is `google_container_cluster.primary` (referenced by depends_on) already created at the time when you run the terraform operation that produces this error?

The cluster is not ready yet. I want to create it at the same time as my deployment.

**Comment by alexsomesan** [comment]
So there's the issue. Unlike the Kubernetes and Helm providers, this provider doesn't support creating the cluster at the same time. The reason is that this provider requires access to the cluster API at plan time, to extract schema information for its resources from the cluster OpenAPI spec.

You would have to perform the cluster creation in a separate apply operation which should finish before applying any `kubernetes_manifest` resources.

This is also explained in the usage docs, here: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/master/docs/usage.md

**Comment by anyght** [comment]
> So there's the issue. Unlike the Kubernetes and Helm providers, this provider doesn't support creating the cluster at the same time. The reason is that this provider requires access to the cluster API at plan time, to extract schema information for its resources from the cluster OpenAPI spec.
> 
> You would have to perform the cluster creation in a separate apply operation which should finish before applying any `kubernetes_manifest` resources.
> 
> This is also explained in the usage docs, here: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/master/docs/usag

**Comment by Kampe** [comment]
This just isn't an acceptable resolution.  Why does this act any differently then the current kubernetes provider....
