### ISSUE TITLE
Basic validation on metadata

### ISSUE THREAD

**Issue by alexsomesan** [hashicorp/terraform-provider-kubernetes-alpha#21]
### Terraform Version and Provider Version
```
Terraform v0.12.24
+ provider.kubernetes-alpha (unversioned)
```

### Affected Resource(s)
All resources

### Expected Behavior
The provider should not attempt to create resources with incomplete metadata. 

### Actual Behavior
Provider passes the resource configuration AS IS to the K8s API and the errors returned are not always very meaningful. 

In the case of attempting to create a namespaced resource without specifying a namespace in configuration, the resulting error is "resource not found".

### Important Factoids
There should be some minimal validation in place to gatekeep from attempting to create resources with invalid / incomplete metadata.

**Comment by mweichert** [comment]
Watching

**Comment by dhirschfeld** [comment]
Ended up here from #48. Commenting for future searchability.
