### ISSUE TITLE
Use Existing YAML as Resource Input?

### ISSUE THREAD

**Issue by kevinbirch** [hashicorp/terraform-provider-kubernetes-alpha#44]
### Description

The current design requires kubernetes resources to be migrated from their native YAML format to HCL.  This can be burdensome requirement when there are a large number YAML files in use.  Instead, what about a new field on the `kubernetes_manifest` resource, which is mutually exclusive with `manifest`, that takes a YAML literal as input.  This new field could be called `manifest_file` for example.  This way the `file` function or heredoc syntax could be used to present existing manifests to Terraform and ease the transition.

### Potential Terraform Configuration

Example using the `file` function:

```hcl
resource "kubernetes_manifest" "service" {
  provider = kubernetes-alpha

  manifest_file = file("path/to/service.yml")
}
```

Example using heredoc syntax:

```hcl
resource "kubernetes_manifest" "service" {
  provider = kubernetes-alpha

  manifest_file = <<EOT
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: "${var.name}"
    app.kubernetes.io/managed-by: Terraform
    app.kubernetes.io/name: vault-agent-injector
  name: "${var.name}-vault-agent-injector-svc"
namespace: "${var.namespace}"
spec:
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/instance: "${var.name}"
    app.kubernetes.io/name: vault-agent-injector
    component: webhook
  clusterIP: "10.96.1.1"
EOT
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Hi @kevinbirch,

Thanks for giving the provider a try. 

We actually considered (and even started prototyping) that exact feature, but then we realized, the same effect can just as easily be achieved with the manifest resource.

Why not just use the Terraform built-in function for decoding YAML to HCL and do something like:
```hcl
resource "kubernetes_manifest" "service" {
  provider = kubernetes-alpha

  manifest = yamldecode(file("path/to/service.yml"))
}
```

Of course, the big downside of doing it in-line like above is that you lose the ability to customize the resource manifest with values from other resources, like is usual in Terraform.

**Comment by kevinbirch** [comment]
> We actually considered (and even started prototyping) that exact feature, but then we realized, the same effect can just as easily be achieved with the manifest resource.
> 
I didn't realize that this function existed, so that is a great solution when interpolation isn't needed.  Please do mention this specifically in the forthcoming documentation for this resource, it's a very handy tip.

Is it syntactically valid to place a heredoc inside an invocation of the `yamldecode` function like this?  (I suspect the answer is "no", it would pass type constraints but the parser may not allow it.)

```hcl
resource "kubernetes_manifest" "service" {
  provider = kubernetes-alpha

  manifest = yamldecode(<<EOT
# lots of yaml goes here
EOT)
}
```

If the above is legal, the we can also have a way provide interpolation as well.  An alternative would be to introduce an `interpolate(string)` function which expands all references.  It could be stacked like so:

```hcl
resource "kubernetes_manifest" "service" {
  provider = kubernetes-alpha

  manifest = yamldecode(interpolate(file("path/to/service.yml")))
}
```

**Comment by jrhouston** [comment]
Terraform has a [template](https://www.terraform.io/docs/providers/template/index.html) provider you can use to interpolate variables in non terraform code. You could use this and then pass into yamldecode()

**Comment by paultyng** [comment]
@kevinbirch that is valid, but it would need to be:

```terraform
manifest = yamldecode<<YAML
# yaml goes here!
YAML
) # note the paren on this other line, the heredoc symbol has to be on its own line i believe
```

See https://www.terraform.io/docs/configuration/expressions.html#string-literals

**Comment by kevinbirch** [comment]
> that is valid

That's great, then it sounds like I have everything I need!  Thanks for your support and a great product.

**Comment by thomas-riccardi** [comment]
Reading the [blogpost](https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform/) lead me to initially think this was sadly not possible to read yaml from files with this new terraform provider.
The [README](https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform/) also doesn't talk about that possibility.

It's however possible, great ! And it's a great replacement for https://github.com/banzaicloud/terraform-provider-k8s (use case: get yaml from github raw, as it's often documented to deploy some applications (then split it into individual resources to keep terraform happy).

So, maybe this feature could be documented in https://github.com/hashicorp/terraform-provider-kubernetes-alpha#moving-from-yaml-to-hcl ? at least pointing to this issue ?
