### ISSUE TITLE
Resources Specific to Common Manifest Types

### ISSUE THREAD

**Issue by kevinbirch** [hashicorp/terraform-provider-kubernetes-alpha#45]
### Description

The current generic resource will work with any Kuberenetes manifest, but there are several manifest types that appear very frequently.  It would be nice to have resources specific to these manifest kinds to reduce syntax fatigue.

### Potential Terraform Configuration

In the examples, the resource names includes the API version for that manifest's schema.  This allows the `apiVersion` and `kind` fields to be elided.  In addition, known fields from the manifest are elevated to fields in the resource schema so they no longer need to be generic list or map assignment expressions.  These include `metadata` (at any level), `spec`, `spec/selector`, `spec/template`, `spec/template/spec`, etc.  Manifest fields with a list value type would follow the HCL convention of repeated occurrences being collapsed into an implied list (e.g. `spec/template/spec/containers` and `spec/template/spec/containers/ports`).

```hcl
resource "kubernetes_deployment_v1" "deployment" {
  metadata {
    labels = {
      app = nginx
    }
    name      = nginx-deployment
    namespace = default
  }

  spec {
    replicas = 3
    selector {
      matchLabels = {
        app = nginx
      }
    }

    template {
      metadata {
        labels = {
          app = nginx
        }
      }

      spec {
        containers {
          image = nginx:1.14.2
          name  = nginx
          ports {
            containerPort = 80
            protocol      = TCP
          }
        }
      }
    }
  }
}

resource "kubernetes_configmap_v1" "configmap" {
  provider = kubernetes-alpha

  metadata {
    name      = test-config
    namespace = default
  }

  data = {
    foo = bar
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Redeux** [comment]
Thanks for the issue, Kevin.  Resources specific to common manifests types are available in the [original Kubernetes provider](https://github.com/terraform-providers/terraform-provider-kubernetes).  Our intent is to move the manifest resource from this provider into the original Kubernetes provider when we feel it's stable.  For now, you can use the two providers side-by-side.

For the time being, you'll have to [download the original Kubernetes provider](https://releases.hashicorp.com/terraform-provider-kubernetes/) and place it in the plugin directory with this provider.
