### ISSUE TITLE
no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by dmaasland** [hashicorp/terraform-provider-kubernetes-alpha#46]
Hiya,

I'm unable to get the examples working when using GKE.

### Terraform Version and Provider Version
```user@ubuntu-dev:~/projects$ terraform -v
Terraform v0.12.26
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
As found here: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/master/examples/deployment/deployment.tf
```hcl
provider "kubernetes-alpha" {
}

resource "kubernetes_manifest" "test-deployment" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "apps/v1"
    "kind"       = "Deployment"
    "metadata" = {
      "labels" = {
        "app" = "nginx"
      }
      "name"      = "nginx-deployment"
      "namespace" = "default"
    }
    "spec" = {
      "replicas" = 3
      "selector" = {
        "matchLabels" = {
          "app" = "nginx"
        }
      }
      "template" = {
        "metadata" = {
          "labels" = {
            "app" = "nginx"
          }
        }
        "spec" = {
          "containers" = [
            {
              "image" = "nginx:1.14.2"
              "name"  = "nginx"
              "ports" = [
                {
                  "containerPort" = 80
                  "protocol"      = "TCP"
                },
              ]
            },
          ]
        }
      }
    }
  }

}
```

### Debug Output
https://gist.github.com/dmaasland/d5efabdf038e96b8abb649bad9180043

### Expected Behavior
Create a plan

### Actual Behavior
Crash with error:
```bash
user@ubuntu-dev:~/projects/test$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: rpc error: code = Unknown desc = no Auth Provider found for name "gcp"
```

### Steps to Reproduce
1. Login to GKE `gcloud container clusters get-credentials <cluster name> --region <region> --project <project>`
2. `terraform plan`

### Important Factoids
I'm using GKE, not standard Kubernetes.

### References
This seems to be related, but I can't seem to apply the fix proposed there:
- https://github.com/hashicorp/terraform/issues/15244

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
Thank you for the report @dmaasland, was there a dev.log file created in the same when you attempted this plan as well? Could you please share the contents?

**Comment by aareet** [comment]
I was able to reproduce this ```❯ kctl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}```
