### ISSUE TITLE
Provider fails to create resource if namespace is not specified

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/terraform-provider-kubernetes-alpha#48]
### Terraform Version and Provider Version
Terraform v0.12.24
kubernetes-provider-alpha 0.1.0

### Affected Resource(s)
kubernetes_manifest

### Terraform Configuration Files

Use the deployment example, but comment out the `namespace`.

https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/master/examples/deployment/deployment.tf

### Debug Output

Full debug trace is here:
https://gist.githubusercontent.com/dak1n1/c8f5f25bf5715f2c8f58966ecc8871e0/raw/f8a4a4162708583a91a6c745ca31904f422f8191/gistfile1.txt

### Expected Behavior
What should have happened?

The provider should either use the `default` namespace when none is specified (like kubectl does) or else provide a meaningful error message.

### Actual Behavior

This error message is returned:

```
Error: rpc error: code = Unknown desc = update dry-run for '/nginx-deployment' failed: the server could not find the requested resource
```

### Steps to Reproduce

1. Grab a copy of the [deployment](https://github.com/hashicorp/terraform-provider-kubernetes-alpha/blob/master/examples/deployment/deployment.tf) example and comment out the `namespace`.

2. Run `terraform apply`.

### Important Factoids

Running on GKE version `1.16.8-gke.15`. Here is a [terraform config to reproduce the environment](https://gist.github.com/dak1n1/57834ab052d99fb66a3906bfdcad9639).

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
This experience should improve once we solve https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/21

**Comment by mweichert** [comment]
Watching

**Comment by dak1n1** [comment]
I applied the reproducer on this one today, using the master branch, and it's still an issue.

**Comment by dak1n1** [comment]
We talked this issue over in the triage meeting today and decided to add a new feature that will choose the namespace `default` when `namespace` is omitted from the `kubernetes_manifest` definition.

**Comment by devurandom** [comment]
Please explain the reasoning for that choice. I would think it would be surprising to the user.

**Comment by alexsomesan** [comment]
The reasoning is that we expect the majority of users of this provider to carry over manifests that they already have in YAML format and currently use with `kubectl`.
Since `kubectl` adopts this behavior of setting the namespace to "default" when none is provided, we anticipate that most manifests out there would be built with that assumption.

**Comment by dhirschfeld** [comment]
Just ran into this issue. My yaml (which worked) didn't specify a namespace so I didn't have one in my `kubernetes-alpha` manifest.

Automatically using the `default` namespace to align with `kubectl` would be an enhancement and nice to have but would also be mostly redundant if the error message said something similar to:
```
Required metadata `namespace` not specified!
```

IMHO fixing the error message is critical to the usability of this tool. It looks like #21 should hopefully cover that though.
