### ISSUE TITLE
Release binary can not be used with hashicorp/terraform docker images

### ISSUE THREAD

**Issue by Starefossen** [hashicorp/terraform-provider-kubernetes-alpha#50]
### Terraform Version and Provider Version

```
$ docker pull hashicorp/terraform:latest
$ docker run hashicorp/terraform:latest version
> Terraform v0.12.26
```

### Affected Resource(s)

- terraform-provider-kubernetes-alpha release binary

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

N/A

### Debug Output

```
$ ./terraform-provider-kubernetes-alpha
> /bin/sh: ./terraform-provider-kubernetes-alpha: not found

$ ldd ./terraform-provider-kubernetes-alpha
        /lib64/ld-linux-x86-64.so.2 (0x7f01ab6b5000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f01ab6b5000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f01ab6b5000)
```

The binary is compiled with dynamic linked libraries (glibc) and since the base image of `hashicorp/terraform` is based on Alpine which uses `musl` and not `glibc` this provider does not work in any of the official docker images for Terraform.

Relase binaries should be built as staticly linked libraries so that they are completely selfcontained as [mentioned here](https://github.com/docker-library/golang/issues/152#issuecomment-283509912) using `-v -ldflags '-d -s -w'` to build static binaries.

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### References

- GH-1234

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by josephpage** [comment]
Hey @Starefossen and guys from @hashicorp, I have submitted one MR to fix the issue : #56
