### ISSUE TITLE
Error in function call

### ISSUE THREAD

**Issue by johan-calle** [hashicorp/terraform-provider-kubernetes-alpha#53]
echo 'yamldecode(file("tests.yaml"))' | terraform console

Error: Error in function call

  on <console-input> line 1:
  (source code not available)

Call to function "file" failed: no file exists at tests.yaml.

**Comment by jrhouston** [comment]
👋 Are you sure there is a file called `tests.yaml` in the directory that you are running that command? 

`yamldecode` and `file` are builtin functions to terraform itself, so there is no bug with the provider in your issue.

The following works for me:

```bash
echo "test: 1" > tests.yaml
echo 'yamldecode(file("tests.yaml"))' | terraform console
{
  "test" = 1
}
```

**Comment by johan-calle** [comment]
hello I already corrected it but that tests.yaml has several kind like for example:
namespace
CustomResourceDefinition
DaemonSet
Deployment
Secret
Ingress

when running the echo 'yamldecode (file ("tests.yaml"))' | terraform console, it only shows me the ingress as terraform format and the others don't.

**Comment by jrhouston** [comment]
The `yamldecode` function in terraform only supports decoding a single YAML document. If you want to convert a manifest with many resources in it you can use [tfks](https://github.com/jrhouston/tfk8s)

**Comment by aareet** [comment]
It seems there's nothing else remaining unresolved here. @johan-calle please reopen if that's not the case, thank you.

**Comment by villesau** [comment]
@jrhouston are you planning on supporting multi resource YAMLs any time soon? For example this cannot be converted using `yamldecode`: https://storage.googleapis.com/gke-release/istio/release/1.0.3-gke.3/patches/install-grafana.yaml

**Comment by jrhouston** [comment]
@villesau `yamldecode()` is part of terraform itself not this provider. I would recommend opening an issue on the main terraform repository requesting the ability to decode files containing multiple YAML documents.

You can also open an issue on this repository if you want to solicit feedback from the community about supporting this directly in the provider.

**Comment by villesau** [comment]
Thank you @jrhouston I also thought it might belong to the main Terraform repo but on the other hand I also think that the issue might be prominent with the new Kubernetes functionality.
