### ISSUE TITLE
no Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by awill1988** [hashicorp/terraform-provider-kubernetes-alpha#54]
### Terraform Version and Provider Version
Terraform v0.12.26
+ provider.kubernetes v1.11.3
+ provider.kubernetes-alpha (unversioned)
+ provider.random v2.2.1

### Affected Resource(s)

- module.metallb.kubernetes_manifest.metallb-system

### Terraform Configuration Files
sys/main.tf
```hcl
provider "kubernetes-alpha" {
  server_side_planning = true
}

provider "kubernetes" {}

terraform {
  backend "local" {
    path = "/Volumes/Shared/terraform/sys/terraform.tfstate"
  }
}

resource "kubernetes_namespace" "namespace" {
  metadata {
    name = "sys"
  }
}

module "metallb" {
  source = "./metallb"
}
```

```hcl
resource "random_string" "secret_material" {
  length = 128
  special = true
  override_special = "/@£$"
}

resource "kubernetes_secret" "secret" {
  metadata {
    namespace = "sys"
    name = "memberlist"
  }

  data = {
    secretkey = random_string.secret_material.result
  }

  type = "Opaque"
}

resource "kubernetes_manifest" "metallb-system" {
  provider = kubernetes-alpha
  manifest = yamldecode(file("./metallb/metallb-system.conf.yml"))
}
```
### Debug Output

https://gist.github.com/awill1988/bac560277d7463a1f529017c653f8b48/raw/fda261648954ccb702537af3efa8e6dc65e57e1c/kubernetes-alpha-debug.log

### Expected Behavior
What should have happened?
`terraform-provider-kubernetes-alpha` would have been able to plan/apply with oidc provider settings in the k8s config.

### Actual Behavior
What actually happened?

Exited with failure with the following message:
`Error: rpc error: code = Unknown desc = no Auth Provider found for name "oidc"`

Oddly enough, I am using the official [Kubernetes Provider](https://www.terraform.io/docs/providers/kubernetes/index.html) without this issue can plan and apply with oidc provider configuration

### Steps to Reproduce

1. Enable OIDC provider in k8s api server as [described in official documentation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server)
2. Set credentials for oidc using kubectl as [described in official documentation](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#using-kubectl)
3. Set current context as shown in [Hashicorp article](https://www.hashicorp.com/blog/deploy-any-resource-with-the-new-kubernetes-provider-for-hashicorp-terraform/)
4. `terraform plan` and observe error output about no oidc provider

### Important Factoids

Not sure if it's atypical to use OIDC authentication for kubectl, but OIDC is configured appropriately and I am able to use kubectl without issue. My OIDC provider is Keycloak.

### References

- #46

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mweichert** [comment]
Watching, as I have the same issue.
