### ISSUE TITLE
Deploying Elasticsearch cluster fails: "the server could not find the requested resource"

### ISSUE THREAD

**Issue by dmaasland** [hashicorp/terraform-provider-kubernetes-alpha#83]
### Terraform Version and Provider Version

```
Terraform v0.12.28
+ provider.kubernetes v1.11.3
+ provider.kubernetes-alpha (unversioned)
```

### Terraform Configuration Files
Converted from: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html
```hcl
provider "kubernetes-alpha" {
  server_side_planning = true
  config_path          = "~/.kube/config"
}

provider "kubernetes" {
  version = "~> 1.11"
}

resource "kubernetes_manifest" "elasticsearch" {
  provider = kubernetes-alpha

  manifest = {
    "apiVersion" = "elasticsearch.k8s.elastic.co/v1"
    "kind"       = "Elasticsearch"
    "metadata" = {
      "name" = "quickstart"
    }

    "spec" = {
      "nodeSets" = [
        {
          "config" = {
            "node.data"             = true
            "node.ingest"           = true
            "node.master"           = true
            "node.store.allow_mmap" = false
          }
          "count" = 1
          "name"  = "default"
        },
      ]
      "version" = "7.8.0"
    }
  }
}
```

### Debug Output

https://gist.github.com/dmaasland/233ca6eac5f226d962e98fddba6ffb66

### Expected Behavior
Elasticsearch cluster created

### Actual Behavior
Error:
```shell
Error: rpc error: code = Unknown desc = update dry-run for '/quickstart' failed: the server could not find the requested resource
```

### Steps to Reproduce

1. Apply ECK yaml: `kubectl apply -f https://download.elastic.co/downloads/eck/1.1.2/all-in-one.yaml`
2. Copy TF code from above
3. `terraform plan`

### Important Factoids

- Running on GKE
- Using steps from https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html
- Applying this step manually versus terraform plan / apply works: https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-elasticsearch.html 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jan-eat** [comment]
You might need to specify/add a namespace in your metadata - have you tried that @dmaasland ?

Original issue: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/48

**Comment by dmaasland** [comment]
Ah, you are correct. Missed that issue, apologies. I currently have another error now:

`Error: rpc error: code = Unknown desc = no matches for elasticsearch.k8s.elastic.co/v1, Resource=Elasticsearch`

But that might be an error on my part somwhere. Thanks! I'll be watching the other issue.

**Comment by aareet** [comment]
@dmaasland looks like this can be closed. Please reopen if that's not the case.
