### ISSUE TITLE
Pre-work to publish to the registry

### ISSUE THREAD

**Issue by aareet** [hashicorp/terraform-provider-kubernetes-alpha#85]
### Description

Publishing the provider to the registry #58 requires some pre-work. 

- [x] Test with [0.13](https://github.com/hashicorp/terraform/releases) to ensure compatibility
- [x] Add formal resource documentation
- [x] Convert existing documentation to the website format
- [x] Align to 0.13 protocol

- [x] Add CLI warning to 0.13 init

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexsomesan** [comment]
Tested with TF 0.13. Seems to work as expected.

**Comment by aareet** [comment]
Provider is now available in the registry https://registry.terraform.io/providers/hashicorp/kubernetes-alpha/latest
