### ISSUE TITLE
Example CRD "test-crd" fails to apply

### ISSUE THREAD

**Issue by quintbotha** [hashicorp/terraform-provider-kubernetes-alpha#87]
### Terraform Version and Provider Version
❯ terraform -v
Terraform v0.12.26
+ provider.kubernetes-alpha (unversioned)

Your version of Terraform is out of date! The latest version
is 0.12.28. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
- crds

### Debug Output
❯ terraform apply

Error: rpc error: code = Unknown desc = update dry-run for '/testcrds.hashicorp.com' failed: Apply failed with 5 conflicts: conflicts with "before-first-apply" using apiextensions.k8s.io/v1:
- .spec.group
- .spec.scope
- .spec.versions
- .spec.names.kind
- .spec.names.plural

### Expected Behavior
CRD should have been created

### Actual Behavior
it failed
Error: rpc error: code = Unknown desc = update dry-run for '/testcrds.hashicorp.com' failed: Apply failed with 5 conflicts: conflicts with "before-first-apply" using apiextensions.k8s.io/v1:
- .spec.group
- .spec.scope
- .spec.versions
- .spec.names.kind
- .spec.names.plural

### Steps to Reproduce
terraform apply

### Important Factoids
just trying to test your crd

### References
Issue 71

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jefflantz** [comment]
Per [Issue #71], make sure that the cluster is running on Kubernetes 1.17. Try running `kubectl version` and looking at the "Server Version" output. If you're trying to deploy to GKE, I elaborate on my solution to that issue.

**Comment by quintbotha** [comment]
I will test this with 1.17.7, I have been running 1.16.10. Will leave feedback here once done

**Comment by quintbotha** [comment]
after upgrading the kubernetes cluster to 1.17.7 the crd was applied successfully with `terraform apply` and destroyed with `terraform destroy`

`kubectl get crds` confirms the creation and destruction

**Comment by placydo** [comment]
This might also occur because of you previously created those resources with different tool (ie. kubectl). Make sure you did clean up before running `terraform apply` - remove all resources you would create with terraform (especially crds).
