### ISSUE TITLE
How to get the privder to work after downloading the release

### ISSUE THREAD

**Issue by james-knott** [hashicorp/terraform-provider-kubernetes-alpha#93]
I had to rename the file in order for terraform to pick it up.

terraform-provider-kubernetes-alpha to terraform-provider-kubernetes-alpha_v0.1.0

**Comment by aareet** [comment]
@james-knott what terraform version are you using?

**Comment by davidov541** [comment]
I'm not OP, but I'm seeing the same behavior in the following environment:

Windows 10 (Version 2004)
Terraform 0.12.21
Kubernetes-Alpha 0.1

**Comment by aareet** [comment]
Closing since it has been a few months waiting for response
