### ISSUE TITLE
FieldManager conflict on second "tf apply"

### ISSUE THREAD

**Issue by jan-eat** [hashicorp/terraform-provider-kubernetes-alpha#96]
I'm trying to apply CRDs and operators from external sources (e.g. ElasticSearch), and they sometimes are of the form as the minimal example below. When applying these for the first time, everything goes smoothly. But subsequent calls to "plan" or "apply" fail - it seems like there is a conflict about who gets to manage some of the "status" fields of the CRD between "Terraform" and "kube-apiserver".

I guess we're using the following request and setting the fieldManager to Terraform:
`PATCH /apis/apiextensions.k8s.io/v1/customresourcedefinitions/myresources.stuff.example.com?dryRun=All&fieldManager=Terraform HTTP/1.1`
and end up with a `FieldManagerConflict`

Is this something that is a bug/can be solved on the terraform side of things, or does the CRD (and the corresponding operator) need to be adjusted?

### Terraform Version and Provider Version
Terraform v0.13.0-beta3
+ provider registry.terraform.io/hashicorp/kubernetes-alpha v0.1.0

### Kubernetes Version
Client: v1.18.6
Server: v1.17.9-gke.600

### Terraform Configuration Files
Minimal example:
```hcl
terraform {
  backend "local" {}
  required_providers {
    kubernetes-alpha = {
      source = "hashicorp/kubernetes-alpha"
    }
  }
  required_version = ">= 0.13"
}


provider "kubernetes-alpha" {}


resource "kubernetes_manifest" "customresourcedefinition_operatorgroups_operators_coreos_com" {
  provider = kubernetes-alpha
  manifest = {
    "apiVersion" = "apiextensions.k8s.io/v1"
    "kind" = "CustomResourceDefinition"
    "metadata" = {
      "creationTimestamp" = null
      "name" = "myresources.stuff.example.com"
    }
    "spec" = {
      "group" = "stuff.example.com"
      "names" = {
        "kind" = "MyResource"
        "listKind" = "MyResourceList"
        "plural" = "myresources"
        "shortNames" = [
          "mr",
        ]
        "singular" = "myresource"
      }
      "scope" = "Namespaced"
      "versions" = [
        {
          "name" = "v1"
          "schema" = {
            "openAPIV3Schema" = {
              "type" = "object"
            }
          }
          "served" = true
          "storage" = true
          "subresources" = {
            "status" = {}
          }
        }
      ]
    }
    "status" = {
      "acceptedNames" = {
        "kind" = ""
        "plural" = ""
      }
      "conditions" = []
      "storedVersions" = []
    }
  }
}
```

### Debug Output
https://gist.github.com/jan-eat/2344fad533aff4fe7aee033ec8c5194e

### Expected Behavior
`terraform plan` succeeds

### Actual Behavior
`terraform plan` fails with an error:
```
Error: rpc error: code = Unknown desc = update dry-run for '/myresources.stuff.example.com' failed: Apply failed with 3 conflicts: conflicts with "kube-apiserver" using apiextensions.k8s.io/v1:
- .status.conditions
- .status.acceptedNames.kind
- .status.acceptedNames.plural
```

### Steps to Reproduce
run the minimal .tf example above to reproduce:
1. Run `terraform init`
2. Run `terraform apply` -- this succeeds
3. Run `terraform plan` -- this produces the error (and so does apply)

I'm running against GKE.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by aareet** [comment]
@jan-eat is there a reason you're setting the `status` field?
```
  "status" = {
      "acceptedNames" = {
        "kind" = ""
        "plural" = ""
      }
      "conditions" = []
      "storedVersions" = []
    }
```

That's set by the kube-apiserver - can you try applying your config without that part in your configuration?

**Comment by aareet** [comment]
Closing, please let us know if that didn't resolve the issue.
